#!/bin/bash

echo "$1"


oldname="$3" newname=${oldname/\.ts/\.mkv} 
newfile=/mnt/disk2/Series/"$2"/"$newname"

mkdir /mnt/disk2/Series/"$2"

/usr/local/bin/ffmpeg -y -nostdin -vcodec mpeg2_mmal -i "$1" -c:a copy -c:v:0 h264_omx -b:v 5000K -r 30 "$newfile" && rm -rf "$1" && ln -s "$newfile" "$1"
