#!/bin/bash


oldname="$3" newname=${oldname/\.ts/\.mkv} 
newfile=/mnt/disk2/Series/"$2"/"$newname"

mkdir /mnt/disk2/Series/"$2"

gst-launch-1.0 filesrc location="$1" ! tsdemux name=demux ! queue ! ac3parse ! matroskamux name=file ! progressreport ! filesink location="$newfile" demux. ! \
queue ! mpegvideoparse ! omxmpeg2videodec ! omxh264enc control-rate=variable target-bitrate=5000000 ! "video/x-h264,profile=high,alignment=au" ! h264parse ! file. 

ln -s "$newfile" "$1"
